apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: testy-fox-nodejs 
  janus-idp.io/tekton: testy-fox-nodejs
  backstage.io/kubernetes-id: testy-fox-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: testy-fox-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  