apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: testy-fox-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testy-fox-nodejs 
  name: testy-fox-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: testy-fox-nodejs 
